config/routes.rb
Rails.application.routes.draw do

  resources :posts
  # get 'sessions/new'

  # get 'sessions/create'

  # get 'sessions/destroy'

  post 'friendships/create' #, controller: 'friendships', action: 'create', as: 'create' 

  delete 'friendships/destroy/:friend_id', controller: 'friendships', action: 'destroy',as: 'destroy'

  root 'users#index'

  devise_for :users
  get 'users/abc'
  resources  :users
  get 'home/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => "User"
	validates :friend_id, uniqueness: {scope: [:friend,:user]} #prevents adding same friend again
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:error] = "That user is already your friend. Try adding New frineds"
      redirect_to root_url
    end
  end
  
  def destroy
    @friendship = current_user.friendships.where(friend_id: params[:friend_id]).first
    #puts "Params #{params[:id]}"
    @friendship.destroy
    flash[:notice] = "Removed friendship."
    redirect_to current_user
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
  	@post = Post.new
  end
  # def create
  # 	@post = Post.new(params[:post])
  #   if @post.save
  #     session[:user_id] = @post.id
  #     flash[:notice] = "Post Created"
  #     redirect_to root_url
  #     else
  #     render :action => 'new'
  #   end
  # end
  def create
  @post = Post.new(params[:post])
 
  @article.save
  redirect_to @article
end

  def destroy
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def show
  	@user = current_user
  end
  def edit
    @user = current_user
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing up! You are now logged in."
      redirect_to root_url
    else
      render :action => 'new'
    end
  end
  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= h(yield(:title) || "Untitled") %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= yield(:head) %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container-fluid">
      <div id="menu">
        <% if user_signed_in? %>
          Welcome <%= current_user.name %>! Not you?
          <%= link_to "Log Out", destroy_user_session_path ,:method=>:delete %> |
          <span class="glyphicon glyphicon-user"></span>&nbsp<%= link_to "View Profile", edit_user_path(current_user) %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path %> or
          <%= link_to "Log In", new_user_session_path %>.
        <% end %>
      </div>

      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>
      <%= yield %>
    </div>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>
<br>
<%= Post %>
<% form_for @post do |f| %>
  <p>
    <%= f.label :post_text %><br />
    <%= f.text_field :post_text %>
  </p>
  <p><%= f.submit "Post" %></p>
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/users/edit.html.erb
<p class="bg-primary"> Profile of <%=h @user.name || @user.email %> </p>
<p><%= link_to "My Friends", user_path(@user.id) %></p>

app/views/users/index.html.erb
<h1>Users' index method Invoked</h1>
<%= "User List" %>

<div id="users">
<% for user in @users %>
  <div class="user">
    <p>
      <strong><%=h user.name || user.email %></strong>
      <%= link_to "Add Friend", friendships_create_path(:friend_id => user), :method => :post %>
      <div class=""></div>
    </p>
  </div>
<% end %>
</div>

app/views/users/new.html.erb
<%= "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<% form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit "Sign up" %></p>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= "My Profile" %>

<p>Username: <%=h @user.name || @user.email %></p>


<h2>Friends</h2>
<ul>
  <% for friendship in @user.friendships %>
    <li>
      <%=h friendship.friend.name %>
      (<%= link_to "remove", destroy_path(friend_id: friendship.friend.id), :method => :delete %>)
    </li>
  <% end %>
</ul>

<p><%= link_to "Find Friends", users_path %></p>

<h2>Friended by Users</h2>
<ul>
  <% for user in @user.inverse_friends %>
    <li><%=h user.name %></li>
  <% end %>
</ul>
<!-- <div class="container">
      <h2>User Glyph</h2>
      <p>User icon: <span class="glyphicon glyphicon-user"></span></p>    
      <p>User icon as a link:
        <a href="#">
          <span class="glyphicon glyphicon-user"></span>
        </a>
      </p>
      <p>User icon on a button:
        <button type="button" class="btn btn-default btn-sm">
          <span class="glyphicon glyphicon-user"></span> User 
        </button>
      </p>
      <p>User icon on a styled link button:
        <a href="#" class="btn btn-info btn-lg">
          <span class="glyphicon glyphicon-user"></span> User 
        </a>
      </p> 
      <p>Unicode:
        <span class="glyphicon">&#xe008;</span>
      </p> 
    </div> -->